accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='all-blog'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/bloggers/', views.BloggerListView.as_view(), name='all-blogger'),
    path('blog/blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    path('blog/', include('blog.urls')),

    # The order is important here because Django looks for URL patterns from top-to-bottom.
    path("accounts/", include("accounts.urls")),
    
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()

# Create your models here.
class Blog(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    post_date = models.DateTimeField(default=timezone.now)
    blogger = models.ForeignKey('Blogger', on_delete=models.RESTRICT, null=True)

    class Meta:
        ordering = ['-post_date']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog-detail", kwargs={"pk": self.pk})

class Blogger(models.Model):
    name = models.OneToOneField(User, on_delete=models.RESTRICT)
    bio = models.TextField()

    def __str__(self):
        return self.name.username
    
    def get_absolute_url(self):
        return reverse("blogger-detail", kwargs={"pk": self.pk})

class Comment(models.Model):
    commentor = models.ForeignKey(User, on_delete=models.RESTRICT)
    post_date = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        return f'{self.commentor.username} -  {self.description[:75]}'

blog/forms.py
from django import forms
from .models import Comment

'''
class Comment(models.Model):
    commentor = models.ForeignKey(User, on_delete=models.RESTRICT)
    post_date = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        return f'{self.commentor.username} -  {self.description[:75]}'
'''

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('description', )

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from .models import Blog, Blogger, Comment
from .forms import CommentForm
from django.http import HttpResponseForbidden
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'index.html')

class BlogListView(ListView):
    model = Blog

class BlogDetailView(DetailView):
    model = Blog
    
    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context
    
class BloggerListView(ListView):
    model = Blogger

class BloggerDetailView(DetailView):
    model = Blogger

blog/templates/blog/blog_detail.html
{% extends "layout.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p>Create on: {{ blog.post_date }}</p>
<p>Author: <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger }}</a></p>
<p>{{ blog.description }}</p>
<br>

<div class='p-4'>
    
    <h3>Comments</h3>
    <hr>
    <ul class="sidebar-nav">
        {% for comment in blog.comment_set.all %}
        <li>
            <div>{{ comment.commentor }} ({{ comment.post_date }})
                - {{ comment.description }}
            </div>
            <hr>
        </li>
        {% endfor %}
    </ul>
    
    {% if user.is_authenticated %}
    <p>Make a comment</p>
    <div class='comment-form'>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
    {% else %}
    <p>login to comment</p>
    {% endif %}
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends "layout.html" %}

{% block content %}
    <h2>All Blog: </h2>
    <ul>
        {% for blog in blog_list %}
            <li><a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> - 
                ({{ blog.post_date }}) - 
                <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

blog/templates/blog/blogger_detail.html
{% extends "layout.html" %}

{% block content %}

<h1>{{ blogger.name }}</h1>
<p>{{ blogger.bio }}</p>

<ul>
    {% for blog in blogger.blog_set.all %}
    <li><a href="{{ blog.get_absolute_url }}">{{blog.name}}</a> - {{blog.post_date}}</li>
    {% endfor %}
</ul>

{% endblock %}

blog/templates/blog/blogger_list.html
{% extends "layout.html" %}

{% block content %}

<h1>All Blogger of the Website:</h1>
<ul>
{% for blogger in blogger_list %}
    <li><a href="{{ blogger.get_absolute_url }}">{{ blogger.name }}</a></li>
{% endfor %}
</ul>

{% endblock %}

blog/templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<h1>Welcome to the Django bloging website</h1>
<img src="{% static "images/diy_django_mini_blog_models.png" %}" alt="DIY django mini blog models uml.">
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Django Blog{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2">
            {% block sidebar %}
              <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'all-blog' %}">All blogs</a></li>
                <li><a href="{% url 'all-blogger' %}">All bloggers</a></li>
              </ul>
              <hr>
              <ul class='sidebar-nav'>
                
                {% if user.is_authenticated %}
                <li>user: {{user.username}}</li>
                <li><p><a href="{% url 'password_change' %}">Password Change</a></p></li>
                <li>
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Log Out</button>
                  </form>
                </li>
                
                {% else %}
                <li><a href="{% url 'login' %}">login</a></li>
                <li><p><a href="{% url 'password_reset' %}">Lost password?</a></p></li>
                <li><a href="{% url 'signup' %}">Sign Up</a></li>
                {% endif %}
              </ul>
            {% endblock %}
          </div>
          <div class="col-sm-10">
            {% block content %}
            <h1>DIY Blog</h1>
            {% endblock %}
        </div>
        </div>
      </div>
      
</body>
</html>